#!/bin/bash

PERL_CPANM_HOME=$COMPLETE_SHELL_TEMP/cpanm
packages_file=$PERL_CPANM_HOME/sources/http%www.cpan.org/02packages.details.txt
cpanm_modules_file=$COMPLETE_SHELL_CACHE/cpanm

export PERL_CPANM_HOME

cpanm --mirror-only CompleteShellDummy &>/dev/null

echo "Fetching '02packages.details.txt' CPAN modules list."
(
  tail -n+10 "$packages_file" |
    cut -d' ' -f1 \
    > "$cpanm_modules_file" &
) &>/dev/null
